// The admin panel's words, in English and Albanian. The choice is kept in the
// browser (localStorage), and starts from the browser's own language.

const EN = {
  htmlLang: 'en',
  title: 'Admin',
  password: 'Password',
  signIn: 'Sign in',
  showPassword: 'Show password',
  hidePassword: 'Hide password',
  devSignIn: 'Sign in without a password (this computer only)',
  signOut: 'Sign out',
  viewSite: 'View the site',
  noPassword: 'No admin password is set yet. On this computer run: npm run admin:password. On the live site set the ADMIN_PASSWORD_HASH secret.',
  errors: {
    wrong_password: 'That password is not right.',
    too_many_attempts: 'Too many tries. Wait 15 minutes and try again.',
    no_password_set: 'No admin password is set yet.',
    network: 'Could not reach the site. Check the connection and try again.',
    server: 'Something went wrong. Try again.',
    bad_file: 'Choose a photo under 3 MB.',
    not_a_photo: 'That file is not a JPEG or WebP photo.',
    bad_size: 'That photo is too small: use one at least 400 pixels wide.',
    photo_read: 'That photo could not be opened. Try a JPEG.',
    too_many_pieces: 'The sheet holds 12 pieces.',
  },
  field: {
    email: 'That does not look like an email address.',
    whatsapp: 'Use 8 to 15 digits, starting with the country code.',
    price: 'A whole number, like 25000.',
    required: 'This is needed.',
    url: 'An address starting with https://, like https://dressesbygreta.com.',
    month: 'Choose a month.',
    profile: 'That is not a profile address on this service.',
    year: 'A year, like 2025.',
    token: 'The token is 32 letters and digits, copied from Cloudflare.',
  },
  nav: { overview: 'Overview', contact: 'Contact', rates: 'Rates', portrait: 'Portrait', graphic: 'Graphic work', quotes: 'Quotes', greta: 'Greta', visits: 'Visits', telegrams: 'Telegrams' },
  on: 'On',
  off: 'Off',
  chip: { live: 'On the site', off: 'Off', needs: 'Needs' },
  needs: {
    whatsapp: 'a WhatsApp number',
    month: 'a month',
    profileLink: 'at least one profile address',
    email: 'a real email address',
    rateItem: 'at least one rate with a name and a price',
    ratesLive: 'the rate card, on and with a rate',
    photo: 'a photo',
    permittedPiece: 'one piece with a photo, a title and permission',
    permittedQuote: 'one quote with permission to publish',
    gretaUrl: 'the address of her site',
    analyticsToken: 'the site token from Cloudflare',
  },
  features: {
    whatsapp: ['WhatsApp button', '“Write on WhatsApp” beside the email links, on the front page, the red Extra sheet and the contact page.'],
    availability: ['Availability', '“Available for new work from October 2026” on the front page, the contact page and the print edition.'],
    links: ['Profile links', 'Instagram, Facebook, LinkedIn and Behance at the foot of every sheet and on the contact page. Search engines learn they are his.'],
    vcard: ['Save to contacts', 'On the contact page: a button that adds Stefano to a phone’s contacts, and a QR code for another screen or for print.'],
    rates: ['Rate card', 'A sheet of prices, set like the rates of a telegraph office.'],
    calculator: ['Price calculator', 'Under the rate card: a visitor ticks what they need, sees the starting total and sends the list in a telegram.'],
    portrait: ['Portrait', 'Stefano’s photo on the About sheet, printed as an engraving. The loupe shows the photograph.'],
    graphic: ['Graphic work', 'A sheet of Stefano’s graphic design after the websites, each piece printed as an engraving. Only pieces the client allows.'],
    quotes: ['Client quotes', 'What clients said, shown only with their permission.'],
    greta: ['Greta’s link', 'A “Visit” button on the Dresses by Greta sheet.'],
    print: ['Print edition', '“Print a copy” in the date line (not on phones); the front page prints as one broadside.'],
    masthead: ['Business front page', 'On the contact page a visitor sets their business name as a front page, then sends it in a telegram.'],
    magnifier: ['Phone magnifier', 'On a phone, hold a screenshot or tap a key letter to see it up close.'],
    analytics: ['Visit counts', 'Cloudflare Web Analytics counts the visits, with no cookies. The privacy notes on the site then say so.'],
  },
  edit: 'Edit',
  overview: {
    head: 'What is on the site',
    launch: 'Before launch',
    emailSet: 'Email: {email}',
    emailMissing: 'Email: not set, so the site still shows hello@example.invalid.',
    passwordSet: 'Admin password: set.',
    passwordMissing: 'Admin password: not set.',
    unread: 'Telegrams: {n} unread.',
    noUnread: 'Telegrams: none unread.',
    parts: 'Optional parts',
    partsNote: 'Each part shows on the site once it is on and has what it needs. Changes appear within a minute of saving.',
    langsNote: 'The site is in English, Albanian and Italian, so each text has a box for every language. The Italian boxes (lighter) may stay empty: the Italian pages then show the English.',
  },
  contact: {
    head: 'Contact',
    email: 'Email address',
    emailHelp: 'Replaces hello@example.invalid everywhere on the site.',
    whatsapp: 'WhatsApp number',
    whatsappHelp: 'With the country code, like +355 69 123 4567. The number is public on the site.',
    test: 'Open it in WhatsApp',
    availability: 'Available for new work from',
    availabilityHelp: 'The month Stefano can start new work. From that month on, the line says “now”.',
    links: 'Profiles',
    linksHelp: 'Paste each profile’s address. For Instagram the name alone is enough, like @stefanodoko.',
    vcardHelp: 'The card carries his name and trade, the country, the email above, and the WhatsApp number while that part is on.',
    qr: 'Download the QR code for print (SVG)',
    qrNeeds: 'The QR code for print appears once the email is set.',
  },
  graphic: {
    head: 'Graphic work',
    item: 'Piece {n}',
    add: 'Add a piece: choose a photo',
    replace: 'Replace the photo',
    uploading: 'Uploading…',
    uploaded: 'Photo saved. Give it a title, then Save.',
    title: 'Title',
    client: 'Client',
    year: 'Year (optional)',
    permission: 'The client allows this piece to be shown',
    help: 'Logos, print, packaging: each piece is printed as an engraving and develops into colour as it is read, and the loupe shows it up close. A photo is kept as soon as it is chosen; its words are kept with Save.',
    empty: 'No pieces yet.',
    max: 'The sheet holds 12 pieces.',
  },
  visits: {
    head: 'Visits',
    token: 'Site token',
    tokenHelp: 'In the Cloudflare dashboard: Web Analytics, Add a site, then copy the token from the snippet it shows (32 letters and digits). The counts are read there, in the dashboard.',
  },
  rates: {
    head: 'Rates',
    currency: 'Currency',
    note: 'A line under the rates (optional)',
    noteHelp: 'For example what the prices include.',
    item: 'Rate {n}',
    name: 'Name',
    desc: 'What it includes',
    price: 'Price',
    from: 'Show it as a starting price (“from”)',
    best: 'A best option: offered first, on the front page',
    group: 'Group on the card',
    groups: { none: 'No group (the top of the card)', sites: 'Websites', design: 'Design', marketing: 'Marketing', extras: 'Add-ons', monthly: 'Every month', season: 'Once a season' },
    unit: 'Per (optional)',
    unitHelp: 'What the price is for, set after it: “/ photo”. A rate in “Every month” shows “/ month” by itself.',
    add: 'Add a rate',
    empty: 'No rates yet.',
    max: 'The card holds {n} rates.',
    fillMenu: 'Put the menu back',
    fillMenuHelp: 'Puts the 24 lines of the menu (the flyers’ and Instagram’s “Menuja”) here, in euros, in place of the list: read them through, then save.',
  },
  portrait: {
    head: 'Portrait',
    none: 'No photo yet.',
    choose: 'Choose a photo',
    replace: 'Replace the photo',
    remove: 'Remove the photo',
    confirmRemove: 'Remove the portrait? The photo is deleted, and the part waits for a new one.',
    confirmYes: 'Remove it',
    confirmNo: 'Keep it',
    uploading: 'Uploading…',
    uploaded: 'Photo saved.',
    help: 'A clear, well-lit photo works best; it is printed as a line engraving. JPEG or WebP, resized here before it is sent.',
    caption: 'Caption (optional)',
  },
  quotes: {
    head: 'Client quotes',
    item: 'Quote {n}',
    text: 'What they said',
    lang: 'Written in',
    translation: 'Translation into {lang} (optional)',
    name: 'Their name',
    business: 'Their business',
    permission: 'They gave permission to publish this, with their name',
    add: 'Add a quote',
    empty: 'No quotes yet.',
    help: 'Only quotes with permission ticked are shown on the site.',
  },
  greta: {
    head: 'Dresses by Greta',
    url: 'Her site’s address',
    urlHelp: 'Once her domain is bought. The front page then shows a “Visit” button on her sheet.',
  },
  telegrams: {
    head: 'Telegrams',
    empty: 'No telegrams yet. They arrive here from the contact page.',
    more: 'Show older ones',
    from: 'From',
    business: 'Business',
    reply: 'Reply to',
    replyIn: 'Reply in',
    received: 'Received',
    markUnread: 'Mark as unread',
    markRead: 'Mark as read',
    delete: 'Delete',
    confirmDelete: 'Delete this telegram for good?',
    keep: 'Keep it',
    close: 'Back to the list',
    unread: 'New',
    cameVia: 'Came via',
    stats: 'This month {started} telegrams were begun and {sent} sent{rate}. Last month: {pstarted} begun, {psent} sent.',
    statsRate: ' ({pct}% of those begun)',
    statsOff: 'Telegrams begun and sent are counted while visits are counted (see Visits).',
  },
  langName: { en: 'English', sq: 'Albanian', it: 'Italian' },
  optional: 'optional',
  move: { up: 'Move up', down: 'Move down', remove: 'Remove' },
  save: { dirty: 'Unsaved changes', saving: 'Saving…', saved: 'Saved. The site shows it within a minute.', button: 'Save changes', discard: 'Discard', fix: 'Some fields need fixing before this can be saved.' },
  months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
};

const SQ = {
  htmlLang: 'sq',
  title: 'Paneli',
  password: 'Fjalëkalimi',
  signIn: 'Hyr',
  showPassword: 'Shfaq fjalëkalimin',
  hidePassword: 'Fshih fjalëkalimin',
  devSignIn: 'Hyr pa fjalëkalim (vetëm në këtë kompjuter)',
  signOut: 'Dil',
  viewSite: 'Shiko faqen',
  noPassword: 'Ende nuk është vendosur fjalëkalim. Në këtë kompjuter nis: npm run admin:password. Në faqen e publikuar vendos sekretin ADMIN_PASSWORD_HASH.',
  errors: {
    wrong_password: 'Fjalëkalimi nuk është i saktë.',
    too_many_attempts: 'Shumë përpjekje. Prit 15 minuta dhe provo sërish.',
    no_password_set: 'Ende nuk është vendosur fjalëkalim.',
    network: 'Faqja nuk u arrit. Kontrollo lidhjen dhe provo sërish.',
    server: 'Diçka shkoi keq. Provo sërish.',
    bad_file: 'Zgjidh një foto më të vogël se 3 MB.',
    not_a_photo: 'Ky skedar nuk është foto JPEG ose WebP.',
    bad_size: 'Kjo foto është shumë e vogël: përdor një me të paktën 400 piksel gjerësi.',
    photo_read: 'Kjo foto nuk u hap dot. Provo një JPEG.',
    too_many_pieces: 'Faqja mban 12 punë.',
  },
  field: {
    email: 'Kjo nuk duket si adresë emaili.',
    whatsapp: 'Përdor 8 deri në 15 shifra, duke nisur me prefiksin e shtetit.',
    price: 'Një numër i plotë, si 25000.',
    required: 'Kjo duhet plotësuar.',
    url: 'Një adresë që nis me https://, si https://dressesbygreta.com.',
    month: 'Zgjidh një muaj.',
    profile: 'Kjo nuk është adresë profili në këtë shërbim.',
    year: 'Një vit, si 2025.',
    token: 'Kodi ka 32 shkronja dhe shifra, i kopjuar nga Cloudflare.',
  },
  nav: { overview: 'Përmbledhje', contact: 'Kontakti', rates: 'Çmimet', portrait: 'Portreti', graphic: 'Punë grafike', quotes: 'Mendimet', greta: 'Greta', visits: 'Vizitat', telegrams: 'Telegramet' },
  on: 'Ndezur',
  off: 'Fikur',
  chip: { live: 'Në faqe', off: 'Fikur', needs: 'I duhet' },
  needs: {
    whatsapp: 'një numër WhatsApp',
    month: 'një muaj',
    profileLink: 'të paktën një adresë profili',
    email: 'një adresë emaili të vërtetë',
    rateItem: 'të paktën një çmim me emër dhe shumë',
    ratesLive: 'listën e çmimeve, të ndezur dhe me një çmim',
    photo: 'një foto',
    permittedPiece: 'një punë me foto, titull dhe leje',
    permittedQuote: 'një mendim me leje për publikim',
    gretaUrl: 'adresa e faqes së saj',
    analyticsToken: 'kodi i faqes nga Cloudflare',
  },
  features: {
    whatsapp: ['Butoni i WhatsApp', '“Shkruaj në WhatsApp” pranë lidhjeve të emailit, në ballinë, në fletën e kuqe «Lajm i fundit!» dhe në faqen e kontaktit.'],
    availability: ['Disponueshmëria', '“I disponueshëm për projekte të reja nga tetori 2026” në ballinë, në faqen e kontaktit dhe në botimin e shtypur.'],
    links: ['Lidhjet e profileve', 'Instagram, Facebook, LinkedIn dhe Behance në fund të çdo faqeje dhe te faqja e kontaktit. Motorët e kërkimit mësojnë se janë të tijat.'],
    vcard: ['Ruaje në kontakte', 'Te faqja e kontaktit: një buton që e shton Stefanon në kontaktet e telefonit dhe një kod QR për një ekran tjetër ose për printim.'],
    rates: ['Lista e çmimeve', 'Një listë me çmimet, e renditur si tarifat e një zyre telegrafi.'],
    calculator: ['Llogaritësi i çmimit', 'Poshtë listës së çmimeve: vizitori shënon atë që i duhet, sheh totalin fillestar dhe e dërgon listën me telegram.'],
    portrait: ['Portreti', 'Fotoja e Stefanos te pjesa “Rreth Stefanos”, e shtypur si gravurë. Lupa tregon fotografinë.'],
    graphic: ['Punë grafike', 'Një faqe me dizajnin grafik të Stefanos pas faqeve të internetit, secila punë e shtypur si gravurë. Vetëm punët që klienti i lejon.'],
    quotes: ['Mendimet e klientëve', 'Çfarë thanë klientët, vetëm me lejen e tyre.'],
    greta: ['Lidhja e Gretës', 'Një buton “Vizito” te pjesa e Dresses by Greta.'],
    print: ['Botimi për shtyp', '“Printo një kopje” te rreshti i datës (jo në telefon); ballina printohet si një fletë e vetme.'],
    masthead: ['Biznesi në ballinë', 'Te faqja e kontaktit vizitori e shkruan emrin e biznesit si ballinë gazete, pastaj e dërgon me telegram.'],
    magnifier: ['Lupa në telefon', 'Në telefon, mbaj gishtin mbi një pamje ose prek një shkronjë për ta parë nga afër.'],
    analytics: ['Numri i vizitave', 'Cloudflare Web Analytics numëron vizitat, pa cookies. Shënimet për privatësinë në faqe e thonë atëherë këtë.'],
  },
  edit: 'Ndrysho',
  overview: {
    head: 'Çfarë ka në faqe',
    launch: 'Para publikimit',
    emailSet: 'Emaili: {email}',
    emailMissing: 'Emaili: i pavendosur, prandaj faqja tregon ende hello@example.invalid.',
    passwordSet: 'Fjalëkalimi i panelit: i vendosur.',
    passwordMissing: 'Fjalëkalimi i panelit: i pavendosur.',
    unread: 'Telegramet: {n} të palexuara.',
    noUnread: 'Telegramet: asnjë i palexuar.',
    parts: 'Pjesët me zgjedhje',
    partsNote: 'Çdo pjesë shfaqet në faqe kur është e ndezur dhe ka atë që i duhet. Ndryshimet duken brenda një minute pasi ruhen.',
    langsNote: 'Faqja është në anglisht, shqip dhe italisht, prandaj çdo tekst ka një kuti për secilën gjuhë. Kutitë në italisht (më të zbehta) mund të mbeten bosh: faqet në italisht tregojnë atëherë tekstin në anglisht.',
  },
  contact: {
    head: 'Kontakti',
    email: 'Adresa e emailit',
    emailHelp: 'Zëvendëson hello@example.invalid kudo në faqe.',
    whatsapp: 'Numri i WhatsApp',
    whatsappHelp: 'Me prefiksin e shtetit, si +355 69 123 4567. Numri shfaqet publikisht në faqe.',
    test: 'Hape në WhatsApp',
    availability: 'I disponueshëm për projekte të reja nga',
    availabilityHelp: 'Muaji kur Stefano mund të nisë projekte të reja. Që nga ai muaj, rreshti thotë “që tani”.',
    links: 'Profilet',
    linksHelp: 'Ngjit adresën e çdo profili. Për Instagram mjafton emri, si @stefanodoko.',
    vcardHelp: 'Kartëvizita mban emrin dhe profesionin, shtetin, emailin më lart dhe numrin e WhatsApp kur ajo pjesë është e ndezur.',
    qr: 'Shkarko kodin QR për printim (SVG)',
    qrNeeds: 'Kodi QR për printim shfaqet sapo të vendoset emaili.',
  },
  graphic: {
    head: 'Punë grafike',
    item: 'Puna {n}',
    add: 'Shto një punë: zgjidh një foto',
    replace: 'Zëvendëso foton',
    uploading: 'Po ngarkohet…',
    uploaded: 'Fotoja u ruajt. Jepi një titull, pastaj Ruaj.',
    title: 'Titulli',
    client: 'Klienti',
    year: 'Viti (me zgjedhje)',
    permission: 'Klienti lejon që kjo punë të shfaqet',
    help: 'Logo, printime, paketime: çdo punë shtypet si gravurë dhe merr ngjyrë ndërsa lexohet, dhe lupa e tregon nga afër. Fotoja ruhet sapo zgjidhet; fjalët ruhen me Ruaj.',
    empty: 'Ende pa punë.',
    max: 'Faqja mban 12 punë.',
  },
  visits: {
    head: 'Vizitat',
    token: 'Kodi i faqes',
    tokenHelp: 'Te paneli i Cloudflare: Web Analytics, Add a site, pastaj kopjo kodin nga copëza që tregon (32 shkronja dhe shifra). Numrat lexohen atje, te paneli.',
  },
  rates: {
    head: 'Çmimet',
    currency: 'Monedha',
    note: 'Një rresht poshtë çmimeve (me zgjedhje)',
    noteHelp: 'Për shembull çfarë përfshijnë çmimet.',
    item: 'Çmimi {n}',
    name: 'Emri',
    desc: 'Çfarë përfshin',
    price: 'Shuma',
    from: 'Shfaqe si çmim fillestar (“nga”)',
    best: 'Opsion i mirë: ofrohet i pari, në faqen kryesore',
    group: 'Grupi në listë',
    groups: { none: 'Pa grup (në krye të listës)', sites: 'Faqet e internetit', design: 'Dizajn', marketing: 'Marketing', extras: 'Shtesat', monthly: 'Çdo muaj', season: 'Një herë në sezon' },
    unit: 'Për (me zgjedhje)',
    unitHelp: 'Për çfarë është çmimi, shkruar pas tij: “/ foto”. Një çmim te “Çdo muaj” shfaq vetë “/ muaj”.',
    add: 'Shto një çmim',
    empty: 'Ende pa çmime.',
    max: 'Lista mban {n} çmime.',
    fillMenu: 'Vendos menunë përsëri',
    fillMenuHelp: 'Vendos këtu 24 rreshtat e menusë (“Menuja” e fletushkave dhe e Instagramit), në euro, në vend të listës: lexoji, pastaj ruaji.',
  },
  portrait: {
    head: 'Portreti',
    none: 'Ende pa foto.',
    choose: 'Zgjidh një foto',
    replace: 'Zëvendëso foton',
    remove: 'Hiq foton',
    confirmRemove: 'Ta heq portretin? Fotoja fshihet dhe pjesa pret një të re.',
    confirmYes: 'Hiqe',
    confirmNo: 'Mbaje',
    uploading: 'Po ngarkohet…',
    uploaded: 'Fotoja u ruajt.',
    help: 'Më mirë një foto e qartë dhe me dritë të mirë; shtypet si gravurë me vija. JPEG ose WebP, e zvogëluar këtu para se të dërgohet.',
    caption: 'Mbishkrimi (me zgjedhje)',
  },
  quotes: {
    head: 'Mendimet e klientëve',
    item: 'Mendimi {n}',
    text: 'Çfarë thanë',
    lang: 'Shkruar në',
    translation: 'Përkthimi në {lang} (me zgjedhje)',
    name: 'Emri i tyre',
    business: 'Biznesi i tyre',
    permission: 'Dhanë leje që ta publikojmë, me emrin e tyre',
    add: 'Shto një mendim',
    empty: 'Ende pa mendime.',
    help: 'Në faqe shfaqen vetëm mendimet që kanë lejen të shënuar.',
  },
  greta: {
    head: 'Dresses by Greta',
    url: 'Adresa e faqes së saj',
    urlHelp: 'Pasi të blihet domeni. Atëherë ballina tregon butonin “Vizito” te pjesa e saj.',
  },
  telegrams: {
    head: 'Telegramet',
    empty: 'Ende pa telegrame. Vijnë këtu nga faqja e kontaktit.',
    more: 'Shfaq telegramet më të vjetra',
    from: 'Nga',
    business: 'Biznesi',
    reply: 'Përgjigju te',
    replyIn: 'Gjuha e përgjigjes',
    received: 'Mbërriti',
    markUnread: 'Shëno si të palexuar',
    markRead: 'Shëno si të lexuar',
    delete: 'Fshi',
    confirmDelete: 'Ta fshij këtë telegram përgjithmonë?',
    keep: 'Mbaje',
    close: 'Kthehu te lista',
    unread: 'I ri',
    cameVia: 'Erdhi nga',
    stats: 'Këtë muaj u filluan {started} telegrame dhe u dërguan {sent}{rate}. Muajin e kaluar: {pstarted} të filluara, {psent} të dërguara.',
    statsRate: ' ({pct}% e të filluarave)',
    statsOff: 'Telegramet e filluara dhe të dërguara numërohen kur numërohen vizitat (shih Vizitat).',
  },
  langName: { en: 'anglisht', sq: 'shqip', it: 'italisht' },
  optional: 'me zgjedhje',
  move: { up: 'Lart', down: 'Poshtë', remove: 'Hiqe' },
  save: { dirty: 'Ndryshime të paruajtura', saving: 'Po ruhet…', saved: 'U ruajt. Faqja e shfaq brenda një minute.', button: 'Ruaj ndryshimet', discard: 'Anulo', fix: 'Disa fusha duhen ndrequr para se të ruhet.' },
  months: ['janar', 'shkurt', 'mars', 'prill', 'maj', 'qershor', 'korrik', 'gusht', 'shtator', 'tetor', 'nëntor', 'dhjetor'],
};

const LANGS = { en: EN, sq: SQ };
let current = 'en';
try {
  const saved = localStorage.getItem('sd-admin-lang');
  current = saved === 'sq' || saved === 'en' ? saved : (navigator.language || '').toLowerCase().startsWith('sq') ? 'sq' : 'en';
} catch { /* storage may be blocked: the browser's language decides */ }

export const T = () => LANGS[current];
export const lang = () => current;
export function setLang(l) {
  current = l === 'sq' ? 'sq' : 'en';
  try { localStorage.setItem('sd-admin-lang', current); } catch { /* not kept */ }
}

/** "{n} unread" with its value filled in. */
export const fill = (s, vars) => s.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''));

/** A date in Albania's time, with month names set by hand (browsers often lack Albanian ones). */
export function when(iso) {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '';
  const p = Object.fromEntries(new Intl.DateTimeFormat('en-GB', {
    day: 'numeric', month: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false, timeZone: 'Europe/Tirane',
  }).formatToParts(d).map((x) => [x.type, x.value]));
  return `${p.day} ${T().months[Number(p.month) - 1]} ${p.year}, ${p.hour}:${p.minute}`;
}
